### ISSUE TITLE
"No copper" zones aren't respected

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#10]
Hi,

Seems that after the conversion the **no copper** zones are not taken into consideration and I get a full copper fill for the board. This happens for both sides of the board. See attached pictures and the original project file.

**Small note:**
  - The "no copper" zones are stacked over the "full copper" zones creating the subtraction effect in the original design.

Conversion:
![conversion_copper_areas](https://user-images.githubusercontent.com/2891463/69627854-2444b000-1054-11ea-9cb0-a1147b75a453.png)

Original:
![Screenshot from 2019-11-26 13-55-09](https://user-images.githubusercontent.com/2891463/69631052-2c055400-1056-11ea-884a-31e569450c55.png)

EasyEDA project:
[Touch_Switch_2ch.zip](https://github.com/wokwi/easyeda2kicad/files/3891725/Touch_Switch_2ch.zip)

**easyeda2kicad version: 1.3.1**

**Comment by urish** [comment]
Alright, pushed a fix - can you please test and report back?

**Comment by mtiutiu** [comment]
Wonderful - you're very skilled sir :). Works like a charm now. Thanks again.

Here's the proof:

![copper_fill_fix](https://user-images.githubusercontent.com/2891463/69640268-bc4b9500-1066-11ea-9c94-974a3f157f38.png)

**Comment by urish** [comment]
Great to see it improving each time :) Thanks for sharing the screenshots
