### ISSUE TITLE
Components package rotation issues

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#11]
Hi,

It seems that this **QFN 48** package is rotated **180** degree after conversion. This happens with other SMD components on the board also like some decoupling capacitors around the QFN 48 IC. Please see attached screenshots.

After conversion:
![package_rotation](https://user-images.githubusercontent.com/2891463/69642537-90321300-106a-11ea-84f1-05219a177db3.png)

Original:
![original_package](https://user-images.githubusercontent.com/2891463/69642552-97f1b780-106a-11ea-98be-795d8dc17961.png)

EasyEDA project:
[Touch_Switch_2ch.zip](https://github.com/wokwi/easyeda2kicad/files/3892319/Touch_Switch_2ch.zip)

I tested it using **latest master code** as it was now at this time of writing.

**Comment by mtiutiu** [comment]
Other components facing the same issue (180 degree rotation). As seen in the pictures those SMD packages are basically flipped.

After conversion:

![rotated_comp_around_ic](https://user-images.githubusercontent.com/2891463/69643200-a391ae00-106b-11ea-98ae-02d5eda84b58.png)

Original:

![original_smd_around_ic](https://user-images.githubusercontent.com/2891463/69643215-aa202580-106b-11ea-8c6b-bb29958b33b3.png)

**Comment by urish** [comment]
So far, it seems to me to rotated components get flipped on the Y-axis, though I haven't managed to figure out a way to determine which ones get flipped

**Comment by mtiutiu** [comment]
@urish Hey, any progress on this? I would really like to "port" some of my projects from EasyEDA to KiCAD. Thanks.

**Comment by urish** [comment]
Hi @mtiutiu , unfortauntely, I haven't had a chance to work in it since. I'll give it another shot this weekend and keep you posted!

Other than this and the shifting, are there any other issues that prevent the EasyEDA → KiCad conversion?

**Comment by mtiutiu** [comment]
> Hi @mtiutiu , unfortauntely, I haven't had a chance to work in it since. I'll give it another shot this weekend and keep you posted!
> 
> Other than this and the shifting, are there any other issues that prevent the EasyEDA → KiCad conversion?

Haven't seen anything else so far.

**Comment by mtiutiu** [comment]
Hi @urish any progress with the current issues? Thanks.

**Comment by urish** [comment]
Hi @mtiutiu , thanks for the ping - I haven't had a chance to look into it since that weekend.

If you do have some time to recreate a minimal example (with just one or two components) that reproduces the issue that could really be helpful to expedite the process

**Comment by mtiutiu** [comment]
Hi @urish 

Sure. Here's another one more simpler:

Original:
![original](https://user-images.githubusercontent.com/2891463/72530967-2cadb000-3879-11ea-9a0e-f8e05a4b6749.png)

Conversion:
![Screenshot from 2020-01-16 15-58-05](https://user-images.githubusercontent.com/2891463/72530978-3505eb00-3879-11ea-93be-75494e8d8c4d.png)

PCB source and result of conversion:

[sample_project.zip](https://github.com/wokwi/easyeda2kicad/files/4071650/sample_project.zip)

I tested it using latest **master** code as it was now at this time of writing.

Let me know if you need additional details. Thanks.

**Comment by urish** [comment]
Thank @mtiutiu !

**Comment by urish** [comment]
Alright, I think I found [the issue](https://github.com/wokwi/easyeda2kicad/commit/cd50297a5b37f2a21c8a52d8d5316df80d6c7e9f#diff-e9f7671dae8faa23f88a00a153691f59R56) after some extensive hunt. Can you please try again and report?

**Comment by mtiutiu** [comment]
Oh man - you're awesome! This fixed it. I want to try with some other boards that I have and report back. Thanks a lot, I really appreciate it.

**Comment by mtiutiu** [comment]
Yep, it seems fine now. I think this ticket can be closed now. Thanks a lot.

**Comment by urish** [comment]
Lovely, I will cut a new release

**Comment by urish** [comment]
Released 1.3.2 with this fix
