### ISSUE TITLE
Unable to open KiCAD pcb file

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#12]
Hi there,

I tried to convert one of my projects to KiCAD and the process seems to be successful (lots of warnings though). When I try to open the generated kicad_pcb file I get this error message and it refuses to go further.

![Screenshot from 2020-01-27 12-44-15](https://user-images.githubusercontent.com/2891463/73168582-c2abcb00-4102-11ea-89a2-0e009662231f.png)

Original PCB:

Top view:
![top](https://user-images.githubusercontent.com/2891463/73169425-b7599f00-4104-11ea-8b4b-94dafce869a5.png)

Bottom view:
![bottom](https://user-images.githubusercontent.com/2891463/73169438-baed2600-4104-11ea-9eac-e4b5f32330f7.png)

**KiCAD** version (latest stable): **5.1.5**
**easyeda2kicad** version: **1.3.2**

Source file used for testing:
[custom_pcb.zip](https://github.com/wokwi/easyeda2kicad/files/4116703/custom_pcb.zip)

Thanks.

**Comment by mtiutiu** [comment]
@urish 

It seems that the generated kicad pcb file had this entry at the end (I opened the file with an text editor): `(xy NaN NaN)`. 
I deleted that entry and I was able to open the PCB design file. I think it was a keep out zone that I defined in EasyEDA but I'm not sure.
The zone fill doesn't seem to be a grid style as in the original picture. But that is because it's not supported in KiCAD 5.1.5.

**Comment by mtiutiu** [comment]
This design is a little bit different as I had to add some overlapping ground fill zones and some floating ground traces over where they intersect. This is because EasyEDA has some bugs when it comes to overlapped ground fill zones or so it seems. So I had to do some ugly "hacks" 😄 . Not ideal I know..but it worked and served to my final purpose.

**Comment by urish** [comment]
Yeah, it seems like the keepout zone uses an SVG arc: `M 4367 3248 A 33.8 33.8 0 1 0 4366.99 3248 Z `
I think this is not directly supported by KiCad, so as a workaround, we'll ignore such zones for now.

**Comment by urish** [comment]
Regarding the hatched fill (grid style) - yea, unfortunately it's not supported by KiCad :-(

**Comment by mtiutiu** [comment]
Works as expected now. Thanks.
