### ISSUE TITLE
Non-GND solid regions are missing after conversion

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#17]
**Description:**
If I have in the original design a **solid copper region** created say for a MOSFET cooling and/or for high current paths which are not tied to GND then those aren't being translated.

**Expected result:**
The solid region tied to MOSFET drain pad should be present on both sides of the PCB.

See attached pictures.

Original:
![original](https://user-images.githubusercontent.com/2891463/73430443-c4fe6700-4346-11ea-9933-9b9bbbe16ff5.png)

Another two pictures (top/bottom) for reference:
![Screenshot from 2020-01-30 10-01-03](https://user-images.githubusercontent.com/2891463/73430785-8d43ef00-4347-11ea-8cbe-cb65666fa0d6.png)
![Screenshot from 2020-01-30 10-00-45](https://user-images.githubusercontent.com/2891463/73430786-8d43ef00-4347-11ea-84a3-ac54198b95c7.png)

Conversion result:
![Screenshot from 2020-01-30 09-49-46](https://user-images.githubusercontent.com/2891463/73430511-f24b1500-4346-11ea-9b2a-76ddb4c0b404.png)

Project files:
[project.zip](https://github.com/wokwi/easyeda2kicad/files/4132817/project.zip)

KiCAD version (latest stable): **5.1.5**
easyeda2kicad version: **1.3.4**

If any other details are needed please let me know.
Thanks.

**Comment by urish** [comment]
May be related to #15 - needs further investigation

**Comment by urish** [comment]
Could be related to #15

**Comment by mtiutiu** [comment]
@urish #15 seems to be fixed now and the symbols are rendered correctly. 
The solid region is still missing though.

**Comment by urish** [comment]
Right, I'll look into this over the next few days

**Comment by urish** [comment]
How about now?

**Comment by mtiutiu** [comment]
Yes sir - that's the spirit! Works like magic now. Thanks a lot.

One small issue is present but that's fixable by hand. It seems that the vias inside that solid region even if they have associated the same net name still don't want to connect.

Other than that - **respect!!!**

![Screenshot from 2020-02-04 12-24-19](https://user-images.githubusercontent.com/2891463/73736436-6d4a6c00-4749-11ea-8b2d-bebab3ae1052.png)

Vias appear like not being connected:
![Screenshot from 2020-02-04 12-27-32](https://user-images.githubusercontent.com/2891463/73736649-d205c680-4749-11ea-8051-7d1666680177.png)

**Comment by urish** [comment]
Thanks for the super-quick feedback! 

Yes, I was looking in KiCad, but it seems like they do not support setting the net names for polygons (I even tried [adding a net attribute](https://github.com/wokwi/easyeda2kicad/blob/408b36e34cccd397ab91423305a3e539193b038c/src/board.ts#L452), but it failed so I commented that out). If you do find a way to do this via KiCad UI, let me know and I will look how to implement it.

**Comment by mtiutiu** [comment]
@urish I think this ticket can be closed as the initial issue was solved. The rest..well maybe other tickets if it's the case.

**Comment by mtiutiu** [comment]
@urish can we have a new release including this fix also if not already there? Thanks.

**Comment by urish** [comment]
Sure, released as 0.4.1
