### ISSUE TITLE
Parts of footprints silkscreen are flipped

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#18]
**Description:**
Some parts of the footprint silkscreen drawing seem to be flipped. This may be related to #9 but I'm not sure if it's the same root cause.

**Expected result:**
Footprints silkscreen should render correctly.

See attached pictures.

Original:
![Screenshot from 2020-01-30 10-01-03](https://user-images.githubusercontent.com/2891463/73432308-1e689500-434b-11ea-954a-16ca5ce8cf31.png)

After conversion:
![Screenshot from 2020-01-30 10-21-54](https://user-images.githubusercontent.com/2891463/73432350-38a27300-434b-11ea-87d9-15472fdefacd.png)

Project files:
[project.zip](https://github.com/wokwi/easyeda2kicad/files/4132912/project.zip)

KiCAD version (latest stable): 5.1.5
easyeda2kicad version: 1.3.4

If any other details are needed please let me know.
Thanks.

**Comment by urish** [comment]
Seems to be related to #16
