### ISSUE TITLE
name of the footprint

### ISSUE THREAD

**Issue by mekesim** [wokwi/easyeda2kicad#3]
It should be better to use EasyEDA package name according to KiCAD footprint name.

![1](https://user-images.githubusercontent.com/4256458/68440683-cc5e1a80-0206-11ea-92d3-cccb8e3f5b91.png)

![2](https://user-images.githubusercontent.com/4256458/68440682-cc5e1a80-0206-11ea-8314-e4e0d5d582c9.png)

**Comment by urish** [comment]
Hi,

I'm not sure what you mean, can you try to explain the example in different words?

Thanks!

**Comment by mekesim** [comment]
Hi,
Thanks for your reply. And thanks for you develop such great tool, that I can covert the PCB from EasyEDA to KiCAD.

My question is:
in EasyEDA the **footprint** name is **package**, in the above pictures, the switch footprint name is SW-TH_4PIN-L6.00-W6.00. However your tool use ID to name the footprint.
So after convert to KiCAD PCB file, the footprint name is gge1136.

So each part will have a unique name. Even some of them use a same footprint.

Anyway, it still work fine.

**Comment by urish** [comment]
I understand now, good point!
I'll have a look at that to see how to fix this.

**Comment by urish** [comment]
Released version 1.2.0 with this fix
