### ISSUE TITLE
Warning: unsupported shape PAD

### ISSUE THREAD

**Issue by opeRaptor** [wokwi/easyeda2kicad#34]
Using the online converter, I am getting "Warning: unsupported shape PAD" errors

Subsequently, the pads in question do not show up on the kicad export.

As footprints export doesn't work as seen in #32 , these footprints were put on a board before export.

Files tested:
https://easyeda.com/component/5b28a2cbfe994fc2a6c4874139cdbdfb
https://easyeda.com/component/b74bc13c9ec64e4b81046b13b757c4dd

**Comment by urish** [comment]
Thanks for reporting! It should be solved with #31

**Comment by opeRaptor** [comment]
Will this fix be pushed to the online tool at https://wokwi.com/easyeda2kicad ?

**Comment by urish** [comment]
Yes, once it is merged it will be. We always keep the online tool up to date with the latest release

**Comment by urish** [comment]
Should be fixed with the latest release, 1.8.0!
