### ISSUE TITLE
>Export Error

### ISSUE THREAD

**Issue by migueltapiar1** [wokwi/easyeda2kicad#41]
Hi, i export my easyeda files to json, then convert them into kicad, when i try to open de kicad file i get this error 
![image](https://user-images.githubusercontent.com/71155501/93145121-7072e680-f6a0-11ea-92ca-d1365b3778ec.png)

I dont know what it means, can you explain me the error please? or what can i do to fix it.

thanks.

**Comment by urish** [comment]
HI, this means that EasyEDA2KiCad could not convert your board correctly. If you attach your EasyEDA source file I can look into it.

**Comment by migueltapiar1** [comment]
I already figure it out, it was a design error with a component i made, thanks.
