### ISSUE TITLE
possible that EDA's footprint format has changed.

### ISSUE THREAD

**Issue by songqiying** [wokwi/easyeda2kicad#50]
all pcb file has one footprint , but it also has wrong .  maby  the  lceda's  footprintf format has changed

[PCB_json.zip](https://github.com/wokwi/easyeda2kicad/files/5899495/PCB_json.zip)

**Comment by songqiying** [comment]
the problem is this .
![lceda2-1](https://user-images.githubusercontent.com/51990528/106423799-15e5f580-649c-11eb-8c68-70ecfb4fa734.png)

I did not know what it is , but if i delet the   (#@$SOLIDREGION...) on  footprint  lable  ,  it is work.

**Comment by urish** [comment]
Thanks for looking for the problem and sharing the screenshot! I hope to look at it on Friday

**Comment by urish** [comment]
Should be fixed in the latest release!
