### ISSUE TITLE
Conversion failed: Error: Missing layer id: 100

### ISSUE THREAD

**Issue by bsaid** [wokwi/easyeda2kicad#51]
How to reproduce the error:

1. Open LCSC parts catalog and find, for example, component C319164 (micro USB female):
     https://lcsc.com/product-detail/USB-Connectors_XKB-Connectivity-U254-051T-4BH23-S2B_C319164.html/
2. Open EasyEDA model by clicking "EasyEDA Model" button and save the EasyEDA board source code.
3. Then try to convert this EasyEDA board to KiCad using this tool.
4. You will see "Conversion failed: Error: Missing layer id: 100"

**Comment by urish** [comment]
Thanks, fixed!
