### ISSUE TITLE
unsupported layer id: 101

### ISSUE THREAD

**Issue by mirkogyo** [wokwi/easyeda2kicad#64]
i got this output

> Running easyeda2kicad v1.9.2:
Reading file C149588.json...
Parsing content...
Detected EasyEDA board (PCB) file.
Warning: unsupported layer id: 101
Warning: unsupported layer id: 100
Warning: unsupported layer id: 100
Warning: unsupported layer id: 99
Warning: unsupported shape SVGNODE in footprint gge30
Writing output to C149588.kicad_pcb...
Conversion done!

but no output file

[C149588.txt](https://github.com/wokwi/easyeda2kicad/files/6676232/C149588.txt)

i attached the file just as a txt because github dont support json as attachment.

thanks for help

**Comment by urish** [comment]
Download issue fixed!
