### ISSUE TITLE
Error in generated KiCad PCB file

### ISSUE THREAD

**Issue by anjonghyun** [wokwi/easyeda2kicad#67]
[파일 변환 오류 보고서.txt](https://github.com/wokwi/easyeda2kicad/files/6775362/default.txt)
![화면 캡처 2021-07-07 165431](https://user-images.githubusercontent.com/86161413/124721716-4f87c480-df44-11eb-8b7c-e530019f3c7d.png)
![화면 캡처 2021-07-07 165419](https://user-images.githubusercontent.com/86161413/124721720-50205b00-df44-11eb-941b-1dad1cbc6f9a.png)

**Comment by urish** [comment]
Can you please upload / add a link to the board file itself (PCB_SU9_STM32_2021-07-07.json) ?

**Comment by anjonghyun** [comment]
[새 폴더.zip](https://github.com/wokwi/easyeda2kicad/files/6775436/default.zip)

**Comment by anjonghyun** [comment]
> [시일 성 오와 이스 리시바 .txt](https://github.com/wokwi/easyeda2kicad/files/6775362/default.txt)
> ![화면 캡처 2021-07-07 165431](https://user-images.githubusercontent.com/86161413/124721716-4f87c480-df44-11eb-8b7c-e530019f3c7d.png)
> ![화면 캡처 2021-07-07 165419](https://user-images.githubusercontent.com/86161413/124721720-50205b00-df44-11eb-941b-1dad1cbc6f9a.png)

**Comment by urish** [comment]
Thanks! I can see this reproduces for me as well.

Looking inside the kicad_pcb file, I can even see what causes the issue:

```
(fp_arc (start NaN NaN) (end -2.05 -1.699) (angle NaN) (width 0.099) (layer "F.SilkS"))
```

I'll investigate where these NaN values from from and fix

**Comment by urish** [comment]
Fixed, thanks for reporting!
