### ISSUE TITLE
Wrong pads orientation for QFN packages

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#7]
Hi,

I tried to convert one of my projects to KiCAD using this utility but it generates pads with wrong orientation for **QFN** packages (**pads** seem to be rotated **90 degree**).
See attached picture. I will attach the project file also if it helps.

Thanks for this little nifty tool.

![wrong_pads_orientation](https://user-images.githubusercontent.com/2891463/69625018-65d25c80-104e-11ea-9d77-b64841ce9764.png)

EasyEDA project:
[Touch_Switch_2ch.zip](https://github.com/wokwi/easyeda2kicad/files/3891736/Touch_Switch_2ch.zip)

**Comment by urish** [comment]
Thanks for reporting! Just to confirm, have you used the latest version of the tool, 1.3.1?

You can print the version number by running: easyeda2kicad -v

**Comment by mtiutiu** [comment]
Also some vias (in this case a ground one) seems to be shifted as seen in the attached pictures. 

Conversion result:

![shifted_gnd_via](https://user-images.githubusercontent.com/2891463/69625673-bf875680-104f-11ea-8116-6ab2e967f00d.png)

Original:
![original](https://user-images.githubusercontent.com/2891463/69625759-f65d6c80-104f-11ea-8b17-17ee0d0a9de8.png)

**Comment by mtiutiu** [comment]
> Thanks for reporting! Just to confirm, have you used the latest version of the tool, 1.3.1?
> 
> You can print the version number by running: `easyeda2kicad -v`

Yep - I cloned your repository and used the latest master code:

```
node dist/main.js -v
Version 1.3.1
```

**Comment by urish** [comment]
I pushed a fix, can you please check (also for #8)?

**Comment by mtiutiu** [comment]
Nice - it's fixed now. Thanks. Issue can be closed now along with #8.

Attaching the result of conversion:
![rotation_fixed](https://user-images.githubusercontent.com/2891463/69633388-c797c400-1058-11ea-80cf-806eb8ca506b.png)

**Comment by urish** [comment]
Awesome! I'm looking into the other other issues now
