### ISSUE TITLE
Double quotes in string not escaped properly

### ISSUE THREAD

**Issue by SukkoPera** [wokwi/easyeda2kicad#73]
Hi, thanks for this great script, first of all!

I tried to convert [this project](https://easyeda.com/editor#id=a4ae24f9d25944dd941b2338bc59c047|ff91d635dfd74f708e79f0ebbe7634b4) but when opening the resulting file in KiCad I get an error at column 35871, regarding a string containing double quotes. It was easy to fix in the generated file but you might want to solve it once for all :).

Attaching the project file: [PCB_Tapuino_v1.0_2021-11-22.json.zip](https://github.com/wokwi/easyeda2kicad/files/7584755/PCB_Tapuino_v1.0_2021-11-22.json.zip)

**Comment by urish** [comment]
thanks for reporting, fixed!
