### ISSUE TITLE
Rectangular SMD pads seem to be 90 degree rotated

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#8]
Hi,

I noticed that some rectangular pads are rotated also causing collisions with vias (in this case a ground one). Attached is the project file also.

Conversion result:
![shifted_gnd_via](https://user-images.githubusercontent.com/2891463/69626196-d2e6f180-1050-11ea-9bc2-10910f09b3df.png)

Original:
![original](https://user-images.githubusercontent.com/2891463/69626214-db3f2c80-1050-11ea-9c90-e8d7916a7761.png)

EasyEDA project:
[Touch_Switch_2ch.zip](https://github.com/wokwi/easyeda2kicad/files/3891617/Touch_Switch_2ch.zip)

**easyeda2kicad version: 1.3.1**

**Comment by urish** [comment]
Are you sure the VIA is shifted? It seems in the correct place to me, just XL1/XL2 pads are rotated? Perhaps this is the same issue as #7

**Comment by mtiutiu** [comment]
Sorry, you're right. I was in a rush and took the wrong conclusion. The pads for that crystal are rotated actually and collides with the GND via.

**Comment by mtiutiu** [comment]
Indeed this may be related to #7 .

**Comment by urish** [comment]
Cool, I think I know where the problem is - seems like the `width` and `height` attributes need to be rotated according to the part/pad orientation when converting between Kicad and EasyEDA. Looking into it right now

**Comment by mtiutiu** [comment]
Fixed in #7.
