### ISSUE TITLE
Some silkscreen elements are shifted and rotated also

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#9]
Hi,

Seems that some silkscreen component labels get shifted and rotated during the conversion process. See attached screenshots. Original project attached also.

Converted:
![silkscreen_shifted_moved_away](https://user-images.githubusercontent.com/2891463/69626765-fd857a00-1051-11ea-94d3-a2eca2a375fe.png)

Original:
![original](https://user-images.githubusercontent.com/2891463/69626694-cd3ddb80-1051-11ea-8081-897c3bdfa569.png)

EasyEDA project:
[Touch_Switch_2ch.zip](https://github.com/wokwi/easyeda2kicad/files/3891652/Touch_Switch_2ch.zip)

**easyeda2kicad version: 1.3.1**

**Comment by urish** [comment]
Rotation issue sseems to be similar to #9, I'm not sure yet about why the shifting happens - investigating

**Comment by mtiutiu** [comment]
More screenshots to observe the issue (some references are really heavily shifted). 

![Screenshot from 2019-11-26 14-30-00](https://user-images.githubusercontent.com/2891463/69633673-5ad0f980-1059-11ea-9e5c-e9b899d6bd6d.png)

![Screenshot from 2019-11-26 14-31-58](https://user-images.githubusercontent.com/2891463/69633810-98ce1d80-1059-11ea-9bd2-941276ffc12a.png)

**Comment by urish** [comment]
I pushed a fix for the orientation - can you please test now?

shifting hasn't been addressed yet (but should be a bit less noticable with the correct orientation)

**Comment by mtiutiu** [comment]
Yep orientation seems to be fixed now. I think some of the shifting issues are caused by the fact that some components are 180 degree rotated as stated in the #11 issue. If that's true then of course the text gets rotated also creating the illusion of being shifted (well...more or less).

Here's the proof about orientation fix and it seems fine now:

![orientation_fix_silk](https://user-images.githubusercontent.com/2891463/69650073-b5c51980-1076-11ea-88a6-976f35815fbf.png)

**Comment by urish** [comment]
@mtiutiu was this issue fixed as well?

**Comment by mtiutiu** [comment]
@urish Yep, seems so.

**Comment by urish** [comment]
Great!
